### ISSUE TITLE
log: add timestamp key-value to all logs

### ISSUE THREAD

**Issue by vxio** [moov-io/base#109]
We should add a timestamp to all logs using
```go
logger = log.With(logger, "ts", log.DefaultTimestampUTC)

logger.Log("msg", "hello")

// Output:
// ts=2016-01-01T12:34:56Z msg=hello
```

**Comment by InfernoJJ** [comment]
I swear I'm pretty sure it was on it already, but I guess I could be wrong lol.

**Comment by adamdecaf** [comment]
I thought so too, but if we need to add it then let's do it.
