### ISSUE TITLE
log: Context should accept an interface{} instead of a string

### ISSUE THREAD

**Issue by vxio** [moov-io/base#110]
The `Context` interface and related methods should accept an `interface{}` over a `string`.
```go
type Context interface {
	Context() map[string]string // -> map[string]interface{}
}
```

since [writeValue](https://github.com/go-logfmt/logfmt/blob/master/encode.go#L197) will be called by `go-kit/log` to properly encode the string.

**Comment by adamdecaf** [comment]
Do we want this sill? The latest release has `map[string]string` 

https://github.com/moov-io/base/blob/v0.14.0/log/logger.go#L19-L20

**Comment by vxio** [comment]
@adamdecaf Yes, this would be a useful change.
