### ISSUE TITLE
Can't use InMemory SQLite

### ISSUE THREAD

**Issue by alovak** [moov-io/base#114]
PayGate Version: ``

**What were you trying to do?**

use database.InMemorySqliteConfig with `database.NewAndMigrate`

**What did you expect to see?**

connection to database created and database migrated

**What did you see?**

err:"no such table: items"

**Comment by alovak** [comment]
As result of solving a [go-migrate/migrate issue](https://github.com/golang-migrate/migrate/issues/97) that does not close connection on passe DB instance we decided to create two DB instances: one for application and another for migrations.

Due to specific of SQLite with `:memory` filename we can't open two separate database connections to the same database: 

> Every :memory: database is distinct from every other. So, opening two database connections each with the filename “:memory:” will create two independent in-memory databases. [source](https://www.sqlite.org/inmemorydb.html)

I see following options here:
1. Drop the support of in-memory SQLite -> it may will impact tests performance; we will need to update our CreateTestSqliteDB to support parallel tests (use random db files for each DB)
2. Fix https://github.com/golang-migrate/migrate (or create a fork) -> it will take some time to get the fix accepted
3. Find different migrator package -> may have some other issues

Any other options?

**Comment by adamdecaf** [comment]
Is this an issue still? We talked about using `?cache=shared` to resolve this.

**Comment by alovak** [comment]
Yep. It's still an issue when we call `NewAndMigrate` method it does following inside:
```
connect to db
run migration
close connection # after we close DB here, we lose all data

connect to db
return connection to caller to be used in repos
```

**Comment by vxio** [comment]
@alovak We've removed `database.InMemorySqliteConfig` in #115 due in part to the issues you described above.

In PayGate, I recommend using `database.CreateTestSQLiteDB(t)`
