### ISSUE TITLE
logging: add a method for logging string slices

### ISSUE THREAD

**Issue by vxio** [moov-io/base#133]
We can do 
```go
logger.Set("orgIDs", log.String(fmt.Sprintf("[%s]",strings.Join(organizationIDs, ","))))
```
but a string array method would be helpful:
```go
logger.Set("orgIDs", log.Strings(organizationIDs))
```
Both would output `orgIDs=["id-1", "id-2", "id-3"]`

-----
Type signature for the valuer would be:
```go
func Strings(vals []string) Valuer
```

**Comment by adamdecaf** [comment]
What would the type signature for `Strings` be?

**Comment by vxio** [comment]
@adamdecaf good point, I updated the description to include the type signature.

**Comment by adamdecaf** [comment]
LGTM. @InfernoJJ ?
