### ISSUE TITLE
Split migrations by environment (prod, staging, etc.)

### ISSUE THREAD

**Issue by atonks2** [moov-io/base#149]
The database package currently supports running a different set of migrations based on the database specified in the config (sqlite or mysql currently). We should support something similar, but have one set of migrations for prod and another set for staging. You can see the sqlite vs mysql migrations at work here: https://github.com/moov-io/base/blob/b5da0698ab8f9808a9f36511d5e4ee6cf2fb557f/database/migrator.go#L20

**Comment by adamdecaf** [comment]
I'm not sure how well this fits into moov-io/base as an OSS library. Could we implement this in the specific application by calling RunMigrations with a different pkger source? The specific application could load the additional migrations and run them on startup.

**Comment by atonks2** [comment]
That's a good call. I'll go that route.

**Comment by InfernoJJ** [comment]
I don’t see a use to this as you want all the environments to run the same
thing to remove possible issues.

**Comment by atonks2** [comment]
That makes sense. In retrospect I jumped to a broad solution to a very specific issue. I'll close this.

**Comment by adamdecaf** [comment]
I think a function that'll take a PkgerSource and run migrations would be helpful. That way applications can run additional sets of migrations without copying the code from RunMigrations.
