### ISSUE TITLE
idempotent: create redis implementation

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/base#16]
From the `X-Idempotency-Key` issue (https://github.com/moov-io/paygate/issues/15#issuecomment-432066409) we want to implement a redis implementation of `idempotent.Recorder`.

There's https://github.com/rafaeljusto/redigomock which looks like it works with https://github.com/gomodule/redigo. It's GPL'd though. 

@wadearnold That project is GPL v2, can we use that? Probably not?
https://github.com/rafaeljusto/redigomock/blob/master/LICENSE

See: https://github.com/moov-io/paygate/issues/21

**Comment by wadearnold** [comment]
Not sure the best solution so let's discuss. 

Ideally, a different license library would exist but this is something I assume we will need to deal with. 

I was trying to fix the GPL issue with the FOSSA project but it was digging down into dependencies of GoLang. 
https://fossa.io/


We could also just add a page to moov.io/licenses 


**GPL USAGE**
The software used by Moov products contain copyrighted software that is licensed under the GPL.

A copy of that license for Version 2.1 is referenced [here](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html) and for version 3.0 [here](https://www.gnu.org/licenses/lgpl-3.0.en.html).

You may obtain the complete Corresponding Source code at no charge from us by reviewing the project dependencies or contacting the project authors.

**Comment by adamdecaf** [comment]
We could use https://github.com/go-redis/redis also and run a redis with docker if needed.
