### ISSUE TITLE
ID() should be more unique 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/base#72]
The existing implementation of `ID() string` only creates random hex strings. There's nothing to ensure uniqueness. We should migrate to something which does.

Currently our stack cares these strings are 40 characters long and of hex strings to strip them from Prometheus paths. (e.g. `GET /users/fffffffffffffff/accounts` to `get-users-accounts`)

Candidates
- https://github.com/gofrs/uuid

**Comment by adamdecaf** [comment]
cc @InfernoJJ

**Comment by adamdecaf** [comment]
I think we should deprecate `ID() string` and use UUID's everywhere.

**Comment by vxio** [comment]
Google's uuid pkg would be a good candidate: https://github.com/google/uuid

**Comment by adamdecaf** [comment]
Yep. I'm pretty indifferent which UUID library we use. Ideally one with as few dependencies as possible.
